# Individual Assignment 1
## Hayden Horn
### 1/26/2022 Spring semester

In [1]:
import numpy as np
from PIL import Image
from prettytable import PrettyTable
from numpy import random

In [4]:
arr1=np.array([[10,20 ], [30,40]])
print(arr1)

[[10 20]
 [30 40]]


In [10]:
np.multiply(arr1,arr1)

array([[ 100,  400],
       [ 900, 1600]])

In [11]:
np.add(arr1,100)

array([[110, 120],
       [130, 140]])

In [12]:
np.multiply(arr1,5)

array([[ 50, 100],
       [150, 200]])

In [13]:
np.sqrt(arr1)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

In [22]:
arr2=np.array([[3,6,9],
               [12,15,18],
               [21,24,27]])
arr2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [23]:
arr3=np.array([[11,12,13],
               [14,15,16],
               [17,18,19]])
arr3

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [24]:
np.multiply(arr3,arr2)

array([[ 33,  72, 117],
       [168, 225, 288],
       [357, 432, 513]])